version: "3"
services:
  traefik:
    image: "traefik:v2.3"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-secure.http.tls=true"
      # ignore internal TLS issues
      - --serversTransport.insecureSkipVerify=true
      # CS Admin & DNS
      - --entrypoints.cs-admin.address=:50050
      - --entrypoints.dns-udp.address=:53/udp
      # ACME
      # - "--certificatesresolvers.primary.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.primary.acme.storage=acme.json"
      # - "--certificatesresolvers.primary.acme.httpchallenge.entrypoint=web"
    ports:
      - 80:80
      - 443:443
      - 53:53/udp
      - 50050:50050
    env_file: .env
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web-secure"
      # - "traefik.http.routers.api.tls.certresolver=primary"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./acme.json:/acme.json"
      
  cobaltstrike:
    build: .
    container_name: cobaltstrike
    env_file: .env
    volumes:
      - ./data:/opt/cobaltstrike
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      # admin (please, protect this with ip whitelisting)
      - "traefik.tcp.routers.cs-admin.rule=HostSNI(`${DOMAIN}`)"
      - "traefik.tcp.routers.cs-admin.entrypoints=cs-admin"
      - "traefik.tcp.routers.cs-admin.tls=true"
      - "traefik.tcp.routers.cs-admin.tls.passthrough=true"
      - "traefik.tcp.services.cs-admin.loadbalancer.server.port=50050"
      # http
      - "traefik.http.routers.cs-web.rule=Host(`static.${DOMAIN}`)"
      - "traefik.http.routers.cs-web.service=cs-web"
      - "traefik.http.routers.cs-web.entrypoints=web" 
      - "traefik.http.services.cs-web.loadbalancer.server.port=80"
      - "traefik.http.services.cs-web.loadbalancer.server.scheme=http"
      # https
      - "traefik.http.routers.cs-web-secure.rule=Host(`static.${DOMAIN}`)"
      - "traefik.http.routers.cs-web-secure.service=cs-web-secure"
      - "traefik.http.routers.cs-web-secure.entrypoints=web-secure" 
      - "traefik.http.services.cs-web-secure.loadbalancer.server.port=443"
      - "traefik.http.services.cs-web-secure.loadbalancer.server.scheme=https"
      # - "traefik.http.routers.cs-web-secure.tls.certresolver=primary"
      # udp
      - "traefik.udp.routers.cs-dns.entrypoints=dns-udp"
      - "traefik.udp.service.cs-dns.loadbalancer.server.port=53"
